/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jt_performance_ArrayCopy */

#ifndef _Included_org_jt_performance_ArrayCopy
#define _Included_org_jt_performance_ArrayCopy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jt_performance_ArrayCopy
 * Method:    deliverArray
 * Signature: ([B[B[BI)V
 */
JNIEXPORT jboolean JNICALL Java_org_jt_performance_ArrayCopy_deliverArray
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
